# Generated by Django 4.1.5 on 2023-04-27 13:49

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('datetime', models.DateTimeField(verbose_name='date time')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='event_image')),
                ('max_participant', models.IntegerField(blank=True, null=True, verbose_name='max participant (opsional)')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('institution_origin', models.CharField(max_length=50, verbose_name='institution origin')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('proof_payment', models.ImageField(upload_to='payment', verbose_name='Proof of payment')),
                ('payment_check', models.BooleanField(default=False, verbose_name='payment check')),
                ('attendance', models.BooleanField(default=False, verbose_name='attendance')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='attendance time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
