# Generated by Django 4.1.5 on 2023-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='proof_payment',
            field=models.ImageField(blank=True, null=True, upload_to='payment', verbose_name='Proof of payment'),
        ),
    ]
