# Generated by Django 4.1.5 on 2023-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_presence_proof_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='institution_origin',
        ),
        migrations.AddField(
            model_name='presence',
            name='institution',
            field=models.CharField(default='upn', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presence',
            name='proof_payment',
            field=models.ImageField(null=True, upload_to='payment', verbose_name='Proof of payment'),
        ),
    ]
