# Generated by Django 4.1.5 on 2023-04-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_presence_institution_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='Ruang Seminar FTM', max_length=46),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=42, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='institution',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='presence',
            name='name',
            field=models.CharField(max_length=48, verbose_name='name'),
        ),
    ]
