# Generated by Django 4.1.5 on 2023-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_place_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='presence',
            name='proof_payment',
            field=models.ImageField(null=True, upload_to='payment', verbose_name='Proof of payment (image)'),
        ),
    ]
