# Generated by Django 4.1.5 on 2023-05-02 20:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_group_link_event_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(verbose_name='free registration'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number (WhatsApp)'),
        ),
    ]
