# Generated by Django 4.1.5 on 2023-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_is_free_alter_presence_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='open registration'),
            preserve_default=False,
        ),
    ]
