# Generated by Django 4.1.5 on 2023-04-23 15:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('datetime', models.DateTimeField(verbose_name='date time')),
                ('max_participant', models.IntegerField(blank=True, null=True, verbose_name='max participant')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('institution_origin', models.CharField(max_length=30, verbose_name='institution origin')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('proof_payment', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('attendance', models.BooleanField(default=False, verbose_name='attendance')),
                ('datatime', models.DateTimeField(blank=True, null=True, verbose_name='attendance time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.event')),
            ],
        ),
    ]
