# Generated by Django 4.1.5 on 2023-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='status',
        ),
        migrations.AddField(
            model_name='presence',
            name='payment_check',
            field=models.BooleanField(default=False, verbose_name='payment check'),
        ),
    ]
