# Generated by Django 4.1.5 on 2023-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_remove_presence_status_presence_payment_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='datatime',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='presence',
            name='proof_payment',
            field=models.ImageField(upload_to='payment'),
        ),
    ]
